#%RAML 1.0 Trait

queryParameters:
      Source:
        required: true
        type: string
        example:
          "Delhi"
      Destination:
        required: true
        type: string
        example:
          "Noida"
      cabType:
        required: false
        type: string
        example:
          "Mini"
